"use client";

import { useState, useEffect } from "react";
import { useStore, Product } from "@/store";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Search, Plus, Edit, Trash2, ArrowUpDown, PackagePlus } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { toast } from "sonner";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

export default function InventoryPage() {
    const [mounted, setMounted] = useState(false);
    const products = useStore((state) => state.products);
    const categories = useStore((state) => state.categories);
    const suppliers = useStore((state) => state.suppliers);
    const addProduct = useStore((state) => state.addProduct);
    const updateProduct = useStore((state) => state.updateProduct);
    const deleteProduct = useStore((state) => state.deleteProduct);
    const adjustStock = useStore((state) => state.adjustStock);

    const [search, setSearch] = useState("");
    const [isAddDialogOpen, setIsAddDialogOpen] = useState(false);
    const [isEditDialogOpen, setIsEditDialogOpen] = useState(false);
    const [isStockDialogOpen, setIsStockDialogOpen] = useState(false);
    const [currentProduct, setCurrentProduct] = useState<any>(null);
    const [stockAmount, setStockAmount] = useState<number>(0);

    const [newProduct, setNewProduct] = useState({
        name: "", barcode: "", category_id: "", supplier_id: "",
        price: 0, cost: 0, stock: 0, min_stock: 5
    });

    useEffect(() => {
        setMounted(true);
    }, []);

    if (!mounted) return <div className="p-8">Cargando inventario...</div>;

    const filteredProducts = products.filter(p =>
        p.name.toLowerCase().includes(search.toLowerCase()) ||
        p.barcode.includes(search)
    );

    const handleDelete = async (id: string, name: string) => {
        if (confirm(`¿Está seguro de eliminar el producto "${name}"?`)) {
            try {
                await deleteProduct(id);
                toast.success("Producto eliminado exitosamente");
            } catch (error) {
                toast.error("Error al eliminar el producto", { description: "Revisa tu conexión o permisos." });
            }
        }
    };

    const getCategoryName = (id: string) => categories.find(c => c.id === id)?.name || "Desconocida";

    const handleAddProduct = async () => {
        if (!newProduct.name || !newProduct.category_id || newProduct.price <= 0) {
            toast.error("Datos incompletos o inválidos", { description: "Por favor, completa todos los campos requeridos correctamente." });
            return;
        }

        const autoGeneratedBarcode = Math.floor(10000000 + Math.random() * 90000000).toString();

        const productDataToSave = {
            ...newProduct,
            barcode: autoGeneratedBarcode,
            supplier_id: (newProduct.supplier_id === "" || newProduct.supplier_id === "none") ? null : newProduct.supplier_id
        };

        try {
            await addProduct(productDataToSave);
            toast.success("Producto creado exitosamente");
            setIsAddDialogOpen(false);
            setNewProduct({ name: "", barcode: "", category_id: "", supplier_id: "", price: 0, cost: 0, stock: 0, min_stock: 5 });
        } catch (error) {
            toast.error("Error al crear el producto", { description: "Comprueba tu conexión a internet o los permisos de Supabase." });
        }
    };

    const handleEditProduct = async () => {
        if (!currentProduct.name || !currentProduct.category_id || currentProduct.price <= 0) {
            toast.error("Datos incompletos o inválidos");
            return;
        }

        try {
            await updateProduct(currentProduct.id, {
                name: currentProduct.name,
                barcode: currentProduct.barcode,
                category_id: currentProduct.category_id,
                supplier_id: (currentProduct.supplier_id === "" || currentProduct.supplier_id === "none") ? null : currentProduct.supplier_id,
                price: Number(currentProduct.price),
                cost: Number(currentProduct.cost),
                min_stock: Number(currentProduct.min_stock)
            });
            toast.success("Producto actualizado exitosamente");
            setIsEditDialogOpen(false);
        } catch (error) {
            toast.error("Error al actualizar el producto");
        }
    };

    const handleAdjustStock = async () => {
        if (stockAmount === 0 || isNaN(stockAmount)) {
            toast.error("Monto inválido", { description: "El ajuste no puede ser cero." });
            return;
        }
        try {
            await adjustStock(currentProduct.id, stockAmount, stockAmount > 0 ? "MANUAL" : "AJUSTE");
            toast.success("Stock actualizado exitosamente", { description: `Se ajustó ${stockAmount > 0 ? '+' : ''}${stockAmount} unidades a ${currentProduct.name}` });
            setIsStockDialogOpen(false);
            setStockAmount(0);
        } catch (error) {
            toast.error("Error al actualizar el stock");
        }
    };

    const openEditDialog = (product: Product) => {
        setCurrentProduct({ ...product });
        setIsEditDialogOpen(true);
    };

    const openStockDialog = (product: Product) => {
        setCurrentProduct(product);
        setStockAmount(0);
        setIsStockDialogOpen(true);
    };

    return (
        <div className="flex-1 space-y-4 sm:space-y-6 p-4 sm:p-8 pt-4 sm:pt-6 max-w-7xl mx-auto overflow-hidden">
            <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between space-y-4 sm:space-y-0">
                <h2 className="text-2xl sm:text-3xl font-bold tracking-tight text-slate-900">Inventario y Catálogo</h2>
                <div className="flex items-center w-full sm:w-auto">
                    <Button className="w-full sm:w-auto bg-blue-600 hover:bg-blue-700 h-10" onClick={() => setIsAddDialogOpen(true)}>
                        <Plus className="mr-2 h-4 w-4" /> Nuevo Producto
                    </Button>
                </div>
            </div>

            <div className="bg-white p-4 sm:p-6 rounded-xl shadow-sm border border-slate-200 overflow-hidden flex flex-col">
                <div className="flex items-center justify-between space-x-4 mb-4 sm:mb-6">
                    <div className="relative flex-1 max-w-sm">
                        <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-slate-400" />
                        <Input
                            placeholder="Buscar producto por nombre o código..."
                            value={search}
                            onChange={(e) => setSearch(e.target.value)}
                            className="pl-10 h-10"
                        />
                    </div>
                    {/* Aquí podríamos agregar filtros por categoría */}
                </div>

                <div className="rounded-md border border-slate-200 overflow-x-auto">
                    <Table className="min-w-[800px]">
                        <TableHeader className="bg-slate-50">
                            <TableRow>
                                <TableHead className="w-[100px]">Código</TableHead>
                                <TableHead>Producto</TableHead>
                                <TableHead>Categoría</TableHead>
                                <TableHead className="text-right">Precio</TableHead>
                                <TableHead className="text-right">Costo</TableHead>
                                <TableHead className="text-right">Stock</TableHead>
                                <TableHead className="text-right">Acciones</TableHead>
                            </TableRow>
                        </TableHeader>
                        <TableBody>
                            {filteredProducts.length === 0 ? (
                                <TableRow>
                                    <TableCell colSpan={7} className="text-center h-24 text-slate-500">
                                        No se encontraron productos.
                                    </TableCell>
                                </TableRow>
                            ) : (
                                filteredProducts.map((product) => (
                                    <TableRow key={product.id}>
                                        <TableCell className="font-mono text-xs text-slate-500">{product.barcode}</TableCell>
                                        <TableCell className="font-medium">{product.name}</TableCell>
                                        <TableCell>
                                            <Badge variant="outline" className="bg-slate-100 text-slate-700">
                                                {getCategoryName(product.category_id)}
                                            </Badge>
                                        </TableCell>
                                        <TableCell className="text-right font-semibold text-blue-600">S/ {product.price.toFixed(2)}</TableCell>
                                        <TableCell className="text-right text-slate-500">S/ {product.cost.toFixed(2)}</TableCell>
                                        <TableCell className="text-right">
                                            <div className="flex items-center justify-end">
                                                {product.stock <= product.min_stock ? (
                                                    <Badge variant="destructive" className="bg-red-100 text-red-700 hover:bg-red-200 border-none">
                                                        {product.stock}
                                                    </Badge>
                                                ) : (
                                                    <span className="font-medium text-slate-700">{product.stock}</span>
                                                )}
                                            </div>
                                        </TableCell>
                                        <TableCell className="text-right">
                                            <div className="flex justify-end space-x-1">
                                                <Button variant="ghost" size="icon" className="h-8 w-8 text-emerald-600 hover:text-emerald-700 hover:bg-emerald-50" title="Agregar Stock" onClick={() => openStockDialog(product)}>
                                                    <PackagePlus className="h-4 w-4" />
                                                </Button>
                                                <Button variant="ghost" size="icon" className="h-8 w-8 text-blue-600 hover:text-blue-700 hover:bg-blue-50" title="Editar" onClick={() => openEditDialog(product)}>
                                                    <Edit className="h-4 w-4" />
                                                </Button>
                                                <Button
                                                    variant="ghost"
                                                    size="icon"
                                                    className="h-8 w-8 text-red-600 hover:text-red-700 hover:bg-red-50"
                                                    onClick={() => handleDelete(product.id, product.name)}
                                                >
                                                    <Trash2 className="h-4 w-4" />
                                                </Button>
                                            </div>
                                        </TableCell>
                                    </TableRow>
                                ))
                            )}
                        </TableBody>
                    </Table>
                </div>
            </div>

            {/* Modal para Agregar Producto */}
            <Dialog open={isAddDialogOpen} onOpenChange={setIsAddDialogOpen}>
                <DialogContent className="sm:max-w-[600px] h-[80vh] overflow-y-auto">
                    <DialogHeader>
                        <DialogTitle>Añadir Nuevo Producto</DialogTitle>
                        <DialogDescription>
                            Completa los datos para registrar un nuevo producto en el inventario.
                        </DialogDescription>
                    </DialogHeader>
                    <div className="grid gap-4 py-4">
                        <div className="grid grid-cols-4 items-center gap-4">
                            <Label htmlFor="add-name" className="text-right font-medium">Nombre *</Label>
                            <Input id="add-name" value={newProduct.name} onChange={(e) => setNewProduct({ ...newProduct, name: e.target.value })} className="col-span-3" />
                        </div>
                        <div className="grid grid-cols-4 items-center gap-4">
                            <Label htmlFor="add-category" className="text-right font-medium">Categoría *</Label>
                            <div className="col-span-3">
                                <Select value={newProduct.category_id} onValueChange={(val) => setNewProduct({ ...newProduct, category_id: val })}>
                                    <SelectTrigger><SelectValue placeholder="Selecciona una categoría" /></SelectTrigger>
                                    <SelectContent>
                                        {categories.map(c => <SelectItem key={c.id} value={c.id}>{c.name}</SelectItem>)}
                                    </SelectContent>
                                </Select>
                            </div>
                        </div>
                        <div className="grid grid-cols-4 items-center gap-4">
                            <Label htmlFor="add-supplier" className="text-right font-medium">Proveedor</Label>
                            <div className="col-span-3">
                                <Select value={newProduct.supplier_id} onValueChange={(val) => setNewProduct({ ...newProduct, supplier_id: val })}>
                                    <SelectTrigger><SelectValue placeholder="Opcional: Selecciona un proveedor" /></SelectTrigger>
                                    <SelectContent>
                                        <SelectItem value="none">Sin Proveedor</SelectItem>
                                        {suppliers.map(s => <SelectItem key={s.id} value={s.id}>{s.name}</SelectItem>)}
                                    </SelectContent>
                                </Select>
                            </div>
                        </div>
                        <div className="grid grid-cols-4 items-center gap-4">
                            <Label htmlFor="add-price" className="text-right font-medium">Precio Venta (S/)*</Label>
                            <Input id="add-price" type="number" min="0" step="0.01" value={newProduct.price} onChange={(e) => setNewProduct({ ...newProduct, price: parseFloat(e.target.value) })} className="col-span-3" />
                        </div>
                        <div className="grid grid-cols-4 items-center gap-4">
                            <Label htmlFor="add-cost" className="text-right font-medium">Costo (S/)</Label>
                            <Input id="add-cost" type="number" min="0" step="0.01" value={newProduct.cost} onChange={(e) => setNewProduct({ ...newProduct, cost: parseFloat(e.target.value) })} className="col-span-3" />
                        </div>
                        <div className="grid grid-cols-4 items-center gap-4">
                            <Label htmlFor="add-stock" className="text-right font-medium">Stock Inicial *</Label>
                            <Input id="add-stock" type="number" min="0" value={newProduct.stock} onChange={(e) => setNewProduct({ ...newProduct, stock: parseInt(e.target.value) })} className="col-span-3" />
                        </div>
                        <div className="grid grid-cols-4 items-center gap-4">
                            <Label htmlFor="add-minstock" className="text-right font-medium">Stock Mínimo</Label>
                            <Input id="add-minstock" type="number" min="0" value={newProduct.min_stock} onChange={(e) => setNewProduct({ ...newProduct, min_stock: parseInt(e.target.value) })} className="col-span-3" />
                        </div>
                    </div>
                    <DialogFooter>
                        <Button variant="outline" onClick={() => setIsAddDialogOpen(false)}>Cancelar</Button>
                        <Button onClick={handleAddProduct} className="bg-blue-600 hover:bg-blue-700">Guardar Producto</Button>
                    </DialogFooter>
                </DialogContent>
            </Dialog>

            {/* Modal para Editar Producto */}
            <Dialog open={isEditDialogOpen} onOpenChange={setIsEditDialogOpen}>
                <DialogContent className="sm:max-w-[600px] h-[80vh] overflow-y-auto">
                    <DialogHeader>
                        <DialogTitle>Editar Producto</DialogTitle>
                        <DialogDescription>
                            Modifica la información básica del producto. El stock solo se puede ajustar por movimientos.
                        </DialogDescription>
                    </DialogHeader>
                    {currentProduct && (
                        <div className="grid gap-4 py-4">
                            <div className="grid grid-cols-4 items-center gap-4">
                                <Label htmlFor="edit-name" className="text-right font-medium">Nombre *</Label>
                                <Input id="edit-name" value={currentProduct.name} onChange={(e) => setCurrentProduct({ ...currentProduct, name: e.target.value })} className="col-span-3" />
                            </div>
                            <div className="grid grid-cols-4 items-center gap-4">
                                <Label htmlFor="edit-category" className="text-right font-medium">Categoría *</Label>
                                <div className="col-span-3">
                                    <Select value={currentProduct.category_id} onValueChange={(val) => setCurrentProduct({ ...currentProduct, category_id: val })}>
                                        <SelectTrigger><SelectValue placeholder="Selecciona una categoría" /></SelectTrigger>
                                        <SelectContent>
                                            {categories.map(c => <SelectItem key={c.id} value={c.id}>{c.name}</SelectItem>)}
                                        </SelectContent>
                                    </Select>
                                </div>
                            </div>
                            <div className="grid grid-cols-4 items-center gap-4">
                                <Label htmlFor="edit-supplier" className="text-right font-medium">Proveedor</Label>
                                <div className="col-span-3">
                                    <Select value={currentProduct.supplier_id || "none"} onValueChange={(val) => setCurrentProduct({ ...currentProduct, supplier_id: val === "none" ? undefined : val })}>
                                        <SelectTrigger><SelectValue placeholder="Selecciona un proveedor" /></SelectTrigger>
                                        <SelectContent>
                                            <SelectItem value="none">Sin Proveedor</SelectItem>
                                            {suppliers.map(s => <SelectItem key={s.id} value={s.id}>{s.name}</SelectItem>)}
                                        </SelectContent>
                                    </Select>
                                </div>
                            </div>
                            <div className="grid grid-cols-4 items-center gap-4">
                                <Label htmlFor="edit-price" className="text-right font-medium">Precio Venta (S/)*</Label>
                                <Input id="edit-price" type="number" min="0" step="0.01" value={currentProduct.price} onChange={(e) => setCurrentProduct({ ...currentProduct, price: parseFloat(e.target.value) })} className="col-span-3" />
                            </div>
                            <div className="grid grid-cols-4 items-center gap-4">
                                <Label htmlFor="edit-cost" className="text-right font-medium">Costo (S/)</Label>
                                <Input id="edit-cost" type="number" min="0" step="0.01" value={currentProduct.cost} onChange={(e) => setCurrentProduct({ ...currentProduct, cost: parseFloat(e.target.value) })} className="col-span-3" />
                            </div>
                            <div className="grid grid-cols-4 items-center gap-4">
                                <Label htmlFor="edit-minstock" className="text-right font-medium">Stock Mínimo</Label>
                                <Input id="edit-minstock" type="number" min="0" value={currentProduct.min_stock} onChange={(e) => setCurrentProduct({ ...currentProduct, min_stock: parseInt(e.target.value) })} className="col-span-3" />
                            </div>
                        </div>
                    )}
                    <DialogFooter>
                        <Button variant="outline" onClick={() => setIsEditDialogOpen(false)}>Cancelar</Button>
                        <Button onClick={handleEditProduct} className="bg-blue-600 hover:bg-blue-700">Actualizar Producto</Button>
                    </DialogFooter>
                </DialogContent>
            </Dialog>

            {/* Modal para Ajustar Stock */}
            <Dialog open={isStockDialogOpen} onOpenChange={setIsStockDialogOpen}>
                <DialogContent className="sm:max-w-[425px]">
                    <DialogHeader>
                        <DialogTitle>Ajustar Stock</DialogTitle>
                        <DialogDescription>
                            Realiza un ajuste manual del inventario para <strong className="text-slate-900">{currentProduct?.name}</strong>. Usa números negativos para restar stock.
                        </DialogDescription>
                    </DialogHeader>
                    <div className="grid gap-4 py-4">
                        <div className="grid grid-cols-4 items-center gap-4">
                            <Label htmlFor="stock-amount" className="text-right font-medium">Cantidad</Label>
                            <Input
                                id="stock-amount"
                                type="number"
                                value={stockAmount}
                                onChange={(e) => setStockAmount(parseInt(e.target.value))}
                                className="col-span-3 text-lg font-mono text-center"
                                placeholder="-5 o 10"
                            />
                        </div>
                        <p className="text-xs text-slate-500 text-center col-span-4 mt-2">
                            Stock resultante previsto: <strong className="text-slate-800">{currentProduct ? currentProduct.stock + (stockAmount || 0) : 0}</strong>
                        </p>
                    </div>
                    <DialogFooter>
                        <Button variant="outline" onClick={() => setIsStockDialogOpen(false)}>Cancelar</Button>
                        <Button onClick={handleAdjustStock} className="bg-emerald-600 hover:bg-emerald-700 text-white border-transparent">Confirmar Ajuste</Button>
                    </DialogFooter>
                </DialogContent>
            </Dialog>
        </div>
    );
}
